# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Helmdiff < Formula
  desc "Diff two Helm chart versions before touching your cluster"
  homepage "https://github.com/jerphil/helmdiff"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jerphil/helmdiff/releases/download/v1.0.0/helmdiff_1.0.0_darwin_amd64.tar.gz"
      sha256 "c2e6cc79fe60abeba65e34beead8c831c65985442dbc7c113e50bf491d8d47b2"

      define_method(:install) do
        bin.install "helmdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jerphil/helmdiff/releases/download/v1.0.0/helmdiff_1.0.0_darwin_arm64.tar.gz"
      sha256 "39f4f9b8ade7ce8ff95348b93f343f75113556bf00faf96613adf6cd5d83c707"

      define_method(:install) do
        bin.install "helmdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jerphil/helmdiff/releases/download/v1.0.0/helmdiff_1.0.0_linux_amd64.tar.gz"
      sha256 "c8ea383ca773b736a3c1d6bf582c705006a55cf5a3f19429a7eee76837d803b5"
      define_method(:install) do
        bin.install "helmdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jerphil/helmdiff/releases/download/v1.0.0/helmdiff_1.0.0_linux_arm64.tar.gz"
      sha256 "a826d7d099c0c707a6a46610b2168817ee665fec00aa8cfcde16550fd7475cbb"
      define_method(:install) do
        bin.install "helmdiff"
      end
    end
  end

  test do
    system "#{bin}/helmdiff", "--version"
  end
end
